swagger: "2.0"
info:
  description: "."
  version: "0.0.0"
  title: "Turku Mobility-Data"
  termsOfService: ""
  contact:
    email: "email@email.com"
host: "127.0.0.1:8000"
basePath: "/mobility_data"

schemes:
- "https"
- "http"
produces:
- application/json

definitions:
  content_type:
    type: object
    title: ContentType
    properties:
      id:
        type: string     
      name: 
        type: string
      description:
        type: string
        
  group_type:
    type: object
    title: GroupType
    properties:
      id:
        type: string     
      name: 
        type: string
      description:
        type: string    
      
  mobility_unit:
    type: object
    title: MobilityUnit
    properties:
      id:
        type: string
      name:
        type: string
      name_fi:
        type: string
      name_sv:
        type: string
      name_en:
        type: string
      description:
        type: string
      description_fi:
        type: string
      description_sv:
        type: string
      description_en:
        type: string
      content_types:
        $ref: "#/definitions/content_type"
      mobile_unit_group:
        $ref: "#/definitions/mobile_unit_group"
      is_active:
        type: boolean
      created_time:
        type: string
      geometry:
        type: string
      geometry_data:
        type: object
        properties:
          x:
            type: number
          y:
            type: number
      unit_id:
        type: integer
      unit_group:
        type: string
      extra:
        type: object
        
  mobile_unit_group:
    type: object
    title: MobilityUnitGroup
    properties:
      id:
        type: string
      name:
        type: string
      name_fi:
        type: string
      name_sv:
        type: string
      name_en:
        type: string
      description:
        type: string
      description_fi:
        type: string
      description_sv:
        type: string
      description_en:
        type: string
      group_type:
        $ref: "#/definitions/group_type"

  
paths:
  /mobile_units/{id}:
    get:
      summary: "Returns a MobileUnit object."
      parameters:
        - name: "id"
          in: path
          type: string
          required: true
        - $ref: "#/components/parameters/srid_param"
      responses: 
        200:
          description: "MobileUnit object"
          schema:
            $ref: "#/definitions/mobility_unit"
      
  /mobile_units/:
    get:
      summary: "Returns a paginated list of MobileUnits."
      parameters:
        - $ref: "#/components/parameters/srid_param"
        - $ref: "#/components/parameters/latlon_param"
        - $ref: "#/components/parameters/type_name_param"
        - $ref: "#/components/parameters/extra_param"
        - $ref: "#/components/parameters/bbox_param"
        - $ref: "#/components/parameters/bbox_srid_param"

      responses:
        200:
          description: "List of MobileUnits."
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: "#/definitions/mobility_unit"
                  
  /mobile_unit_groups/{id}:
    get:
      summary: "Returns a MobileUnitGroup object."
      parameters:
        - name: "id"
          in: path
          type: string
          required: true
        - $ref: "#/components/parameters/srid_param"
        - $ref: "#/components/parameters/latlon_param"
        - $ref: "#/components/parameters/mobile_units_param"
      responses: 
        200:
          description: "MobileUnitGroup object"
          schema:
            $ref: "#/definitions/mobile_unit_group"
            
  /mobile_unit_groups/:
    get:
      summary: "Returns a paginated list of MobileUnitGroups."
      parameters:
        - $ref: "#/components/parameters/srid_param"
        - $ref: "#/components/parameters/latlon_param"
        - $ref: "#/components/parameters/mobile_units_param"
        - $ref: "#/components/parameters/group_name_param"
      responses:
        200:
          description: "List of MobilityUnitGroups."
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: "#/definitions/mobile_unit_group"
  /content_types/{id}:
    get:
      summary: "Returns ContentType object."
      parameters:
        - name: "id"
          in: path
          type: string
          required: true
      responses: 
        200:
          description: "ContentType object."
          schema:
            $ref: "#/definitions/content_type"  
            
  /content_types/:
    get:
      summary: "Returns a paginated list of ContentTypes."
      responses:
        200:
          description: "List of ContentTypes."
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: "#/definitions/content_type"
  /geoup_types/{id}:
    get:
      summary: "Returns GroupType object."
      parameters:
        - name: "id"
          in: path
          type: string
          required: true
      responses: 
        200:
          description: "GroupType object."
          schema:
            $ref: "#/definitions/group_type"  
            
  /group_types/:
    get:
      summary: "Returns a paginated list of GroupTypes."
      responses:
        200:
          description: "List of GroupTypes."
          schema:
            type: object
            properties:
              results:
                type: array
                items:
                  $ref: "#/definitions/group_type"              
components:
  parameters:
    srid_param:
      name: srid
      in: query
      description: Transform to particular srid.
      required: false
      schema:
        type: integer
      example: 4326
    latlon_param:
      name: latlon
      in: query
      description: If set to true, returns geometry_coords field in (lat, lon) format, the default is (lon, lat)
      schema:
        type: boolean
      example: true
      
    type_name_param:
      name: type_name
      in: query
      description: Return only MobileUnits that are of type the given type_name.
      required: false
      schema:
        type: string
      example: GFS
    
    group_name_param:
      name: group_name
      in: query
      description: Return only MobileUnitGroups that are of type the given group_name.
      required: false
      schema:
        type: string
      example: CRE
      
    mobile_units_param:
      name: mobile_units
      in: query
      description: If true return all MobileUnit instances that are in the MobileUnitGroup.
      required: false
      schema:
        type: boolean
      example: true

    extra_param:
      name: extra__
      in: query
      description: Filter with the content of a extra field.
      required: false
      schema:
        type: string
      example: extra__fieldname=value

    bbox_param:
      name: bbox
      in: query
      description: Search for mobile units that are within this bounding box. Decimal coordinates
        are given in order west, south, east, north. Period is used as decimal
        separator. Default srid is 4326.
      schema:
        type: array
        items:
          type: number
      example: 24.9405559,60.1695096,24.9805559,60.1895096
    
    bbox_srid_param:
      name: bbox_srid
        in: query
        description: An SRID coordinate reference system identifier which specifies the
          coordinate system used in the bbox parameter. 
        schema:
          type: integer
        example: 3046